### ISSUE TITLE
0.6.0无法在python2中使用

### ISSUE THREAD

**Issue by shuxiang** [lxneng/xpinyin#54]
pip install xpinyin==0.6.0

>>> import xpinyin
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sx/.local/lib/python2.7/site-packages/xpinyin/__init__.py", line 112
    def get_pinyins(self, chars: str, splitter: str = u'-',
                               ^
SyntaxError: invalid syntax

这个类型声明python2还没有吧~

**Comment by lxneng** [comment]
噢, 是的, 我更新了一下README
请用0.5.7  `pip install xpinyin==0.5.7`
