### ISSUE TITLE
打包运行后出现如下错误

### ISSUE THREAD

**Issue by asian3** [lxneng/xpinyin#56]
Traceback (most recent call last):
  File "Area.py", line 534, in <module>
  File "xpinyin\__init__.py", line 60, in __init__
  File "pathlib.py", line 1175, in read_text
  File "pathlib.py", line 1162, in open
  File "pathlib.py", line 1016, in _opener
  File "pathlib.py", line 388, in wrapped
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\surface\\AppData\\Local\\Temp\\_MEI10162\\Mandarin.dat'

**Comment by nigexiaozhazha** [comment]
打包出错的话，将【xpinyin】下的Mandarin.dat改为，[Mandarin.json]（需手动修改，代码自己写）
然后将__init__.py下的 57行改为：
data_path = Path(__file__).resolve().with_name('Mandarin.json')
__init__函数改为：
    def __init__(self, data_path: str = str(data_path)) -> None:
        # lines = Path(data_path).read_text().splitlines()
        # self.pinyins = dict(tuple(line.split('\t', maxsplit=1)) for line in lines)
        # print(self.pinyins)
        with open(data_path, 'r',encoding='utf-8') as j_r:
            self.pinyins = json.load(j_r)
